ALTER TABLE model_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE inferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE dataset_exports ENABLE ROW LEVEL SECURITY;
